
----- RESPECTO A LA TABLA USUARIOS ------

-- ID_USUARIO NO LO AÑADIMOS EN LA INSTRUCCION DE AÑADIR YA QUE LO HEMOS IMPLEMENTADO QUE CADA VEZ QUE SE INSERTE UN USUARIO SE INCREMENTE AUTOMATICAMENTE

-- PRIMERO VAMOS AÑADIR EL ADMIN --

-- INSERTADO AL FINAL POR CODIGO --

INSERT INTO USUARIOS (NICKNAME, NOMBRE, CORREO, PASSWORD, ROL_USUARIO) VALUES('admin', 'admin', 'admin@ucm', 'adminpass', 'ADMIN');

-- PARA AÑADIR UN USUARIO NORMAL NO HACE FALTA AÑADIR EL CAMPO ROL_USUARIO, PORQUE YA LO HEMOS IMPLEMENTADO DE TAL FORMA QUE CUANDO SE INSERTE UN USUARIO
-- SE PONGA POR DEFECTO EN ESE CAMPO: USER.

INSERT INTO USUARIOS (NICKNAME, NOMBRE, CORREO, PASSWORD) VALUES('alv1', 'Alvaro', 'alvcarpi@ucm.es', '1111');
INSERT INTO USUARIOS (NICKNAME, NOMBRE, CORREO, PASSWORD) VALUES('jhce2', 'Jhimmy Ender', 'jcandela@ucm.es', '2222');
INSERT INTO USUARIOS (NICKNAME, NOMBRE, CORREO, PASSWORD) VALUES('jvp3', 'Jorge', 'jvalma01@ucm.es', '3333');
INSERT INTO USUARIOS (NICKNAME, NOMBRE, CORREO, PASSWORD) VALUES('iif4', 'Iker', 'ikeriban@ucm.es', '4444');
INSERT INTO USUARIOS (NICKNAME, NOMBRE, CORREO, PASSWORD) VALUES('atc5', 'Alberto', 'alberture@ucm.es', '5555');
INSERT INTO USUARIOS (NICKNAME, NOMBRE, CORREO, PASSWORD) VALUES('jjjj6', 'Jonathan Jose', 'jonathanj@ucm.es', '6666');

 -- NO HAGAIS CASO A LAS SIGUIENTES INSERCCIONES --

--INSERT INTO USUARIOS (NICKNAME, NOMBRE, CORREO, PASSWORD) VALUES('jjjj8', 'Jonathan Josa', 'jonathanf@ucm.es', MD5('7777'));
--INSERT INTO USUARIOS (NICKNAME, NOMBRE, CORREO, PASSWORD) VALUES('alv11', 'Alvaroo', 'alvcarpii@ucm', SHA('11111'));
--INSERT INTO USUARIOS (NICKNAME, NOMBRE, CORREO, PASSWORD) VALUES('alv111', 'Alvarooo', 'alvcarpiii@ucm', SHA1('111111'));
--INSERT INTO USUARIOS (NICKNAME, NOMBRE, CORREO, PASSWORD) VALUES('alv22', 'Alvaroor', 'alvcarpiir@ucm', AES_ENCRYPT('2222', '1111'));
--INSERT INTO USUARIOS (NICKNAME, NOMBRE, CORREO, PASSWORD) VALUES('alv24', 'Alvaroorr', 'alvcarpigr@ucm', OLD_PASSWORD('111111'));
--INSERT INTO USUARIOS (NICKNAME, NOMBRE, CORREO, PASSWORD) VALUES('alv55', 'Alvarooff', 'alvcarpihh@ucm', HASH('1111'));
--INSERT INTO usuarios VALUES('usuario',AES_ENCRYPT('contraseña','llave'))

---PARA REINICIAR EL AUTOINCREMENT ---

ALTER TABLE `usuarios`
  MODIFY `ID_USUARIO` int(10) NOT NULL AUTO_INCREMENT, AUTO_INCREMENT=1;


 ------ RESPECTO TABLA DEPORTES ------

-- PARA REINICIAR EL AUTOINCREMENT --
 ALTER TABLE `deportes`
  MODIFY `ID_DEPORTE` int(10) NOT NULL AUTO_INCREMENT, AUTO_INCREMENT=880001;

-- INSERTAR DEPORTES --
INSERT INTO DEPORTES (NOMBRE_DEPORTE,  NUMERO_MAXIMO_JUGADORES, DURACION_MIN, FECHA_CDEPORTE, HORA_CDEPORTE) VALUES('FUTBOL', 20, 90, CURDATE(), CURTIME());
INSERT INTO DEPORTES (NOMBRE_DEPORTE,  NUMERO_MAXIMO_JUGADORES, DURACION_MIN, FECHA_CDEPORTE, HORA_CDEPORTE) VALUES('BALONCESTO', 10, 40, CURDATE(), CURTIME());
INSERT INTO DEPORTES (NOMBRE_DEPORTE,  NUMERO_MAXIMO_JUGADORES, DURACION_MIN, FECHA_CDEPORTE, HORA_CDEPORTE) VALUES('BEISBOL', 10, 60, CURDATE(), CURTIME());
INSERT INTO DEPORTES (NOMBRE_DEPORTE,  NUMERO_MAXIMO_JUGADORES, DURACION_MIN, FECHA_CDEPORTE, HORA_CDEPORTE) VALUES('BALONMANO', 15, 40, CURDATE(), CURTIME());

------ RESPECTO TABLA EQUIPOS ------

-- PARA REINICIAR EL AUTOINCREMENT --
ALTER TABLE `equipos`
  MODIFY `ID_EQUIPO` int(10) NOT NULL AUTO_INCREMENT, AUTO_INCREMENT=550001;

-- INSERTAR EQUIPOS --
INSERT INTO EQUIPOS (DEPORTE, NOMBRE_EQUIPO, FECHA_CEQUIPO, HORA_CEQUIPO, DESCRIPCION_EQUIPO) VALUES(880001, 'BULL', CURDATE(), CURTIME(), 'Somos un equipo de basket');
INSERT INTO EQUIPOS (DEPORTE, NOMBRE_EQUIPO, FECHA_CEQUIPO, HORA_CEQUIPO, DESCRIPCION_EQUIPO) VALUES(880002, 'REAL MADRID', CURDATE(), CURTIME(), 'Somos un equipo de fútbol');
INSERT INTO EQUIPOS (DEPORTE, NOMBRE_EQUIPO, FECHA_CEQUIPO, HORA_CEQUIPO, DESCRIPCION_EQUIPO) VALUES(880003, 'SALOU', CURDATE(), CURTIME(), 'Somos un equipo de beisbol');
INSERT INTO EQUIPOS (DEPORTE, NOMBRE_EQUIPO, FECHA_CEQUIPO, HORA_CEQUIPO, DESCRIPCION_EQUIPO) VALUES(880004, 'VALENCIA', CURDATE(), CURTIME(), 'Somos un equipo de balonmano');

------ RESPECTO TABLA JUGADORES ------

-- PARA REINICIAR EL AUTOINCREMENT --
ALTER TABLE `jugadores`
  MODIFY `ID_JUGADOR` int(10) NOT NULL AUTO_INCREMENT, AUTO_INCREMENT=330001;

-- INSERTAR JUGADORES A EQUIPOS --
INSERT INTO JUGADORES (EQUIPO,  USUARIO, ROL_JUGADOR, FECHA_PJUGADOR, HORA_PJUGADOR) VALUES(550001, 2, TRUE, CURDATE(), CURTIME());
INSERT INTO JUGADORES (EQUIPO,  USUARIO, ROL_JUGADOR, FECHA_PJUGADOR, HORA_PJUGADOR) VALUES(550001, 3, FALSE, CURDATE(), CURTIME());
INSERT INTO JUGADORES (EQUIPO,  USUARIO, ROL_JUGADOR, FECHA_PJUGADOR, HORA_PJUGADOR) VALUES(550002, 4, TRUE, CURDATE(), CURTIME());
INSERT INTO JUGADORES (EQUIPO,  USUARIO, ROL_JUGADOR, FECHA_PJUGADOR, HORA_PJUGADOR) VALUES(550002, 5, FALSE, CURDATE(), CURTIME());
INSERT INTO JUGADORES (EQUIPO,  USUARIO, ROL_JUGADOR, FECHA_PJUGADOR, HORA_PJUGADOR) VALUES(550003, 6, TRUE, CURDATE(), CURTIME());
INSERT INTO JUGADORES (EQUIPO,  USUARIO, ROL_JUGADOR, FECHA_PJUGADOR, HORA_PJUGADOR) VALUES(550003, 7, FALSE, CURDATE(), CURTIME());




------ RESPECTO TABLA EVENTOS ------

-- PARA REINICIAR EL AUTOINCREMENT --
ALTER TABLE `eventos`
  MODIFY `ID_EVENTO` int(11) NOT NULL AUTO_INCREMENT, AUTO_INCREMENT=990001 ;


-- PARA AÑADIR FOREIGN KEY --
ALTER TABLE `eventos`
  ADD CONSTRAINT `eventos_ibfk_1` FOREIGN KEY (`EQUIPO_1`) REFERENCES `equipos` (`ID_EQUIPO`) ON DELETE CASCADE,
  ADD CONSTRAINT `eventos_ibfk_2` FOREIGN KEY (`EQUIPO_2`) REFERENCES `equipos` (`ID_EQUIPO`) ON DELETE CASCADE;
COMMIT;