-- CONSULTAS PARA REALIZAR EN LAS TABLAS DE SPORTS4FRIENDS --

-- EN SQL
-- CUANDO SE REGISTRA UNA PERSONA Y SE CONVIERTE EN USUARIO: OK
INSERT INTO USUARIOS (ID_USUARIO, NICKNAME, NOMBRE,  APELLIDOS, TELEFONO, CORREO, PASSWORD) VALUES (SEQ_IDUSER.NEXTVAL, 'sofi7', 'Sofia', 'Garcia Lopez',677777777, 'susanalopez@gmail.com', 'ss77');
-- CUANDO SE REGISTRA UNA PERSONA, CON EL MISMO NOMBRE QUE OTRA PERSONA, PERO DISTINTO, NICKNAME, CORREO ELECTRONICO Y CON LA MISMA CONTRASEÑA QUE OTRO USUARIO YA REGISTRADO. OK
INSERT INTO USUARIOS (ID_USUARIO, NICKNAME, NOMBRE,  APELLIDOS, TELEFONO, CORREO, PASSWORD) VALUES (SEQ_IDUSER.NEXTVAL, 'sofi8', 'Sofia', 'Garcia Lopez','','susanaalegria@gmail.com', 'ss77');
-- CUANDO SE REGISTA UNA PERSONA CON DISTINTO NOMBRE QUE OTROS USUARIOS, PERO LO HACE CON UNA CUENTA YA REGISTRADA EN LA APP Y DISTINTA CONTRASEÑA. NO OK
INSERT INTO USUARIOS (ID_USUARIO, NICKNAME, NOMBRE,  APELLIDOS, TELEFONO, CORREO, PASSWORD) VALUES (SEQ_IDUSER.NEXTVAL, 'juli9', 'Julia', 'Hernandez Blanco', '', 'susanaalegria@gmail.com', 'yy44');

/* Error que empieza en la línea: 122 del comando :
INSERT INTO USUARIOS (ID_USUARIO, NICKNAME, NOMBRE,  APELLIDOS, TELEFONO, CORREO, PASSWORD) VALUES (9, 'juli9', 'Julia', 'Hernandez Blanco', '', 'susanaalegria@gmail.com', 'yy44')
Informe de error -
ORA-00001: unique constraint (CC16.SYS_C008311) violated
 */

-- REGISTRAR UNA PERSONA SOLO CON UN NOMBRE.OK
INSERT INTO USUARIOS (ID_USUARIO, NICKNAME, NOMBRE,  APELLIDOS, TELEFONO, CORREO, PASSWORD) VALUES (SEQ_IDUSER.NEXTVAL, 'robert10', 'Roberto', 'Ruiz', '', 'robertoruiz@gmail.com', '2223B');
-- REGISTRAR PERSONA SIN CONTRASEÑA. NO OK
INSERT INTO USUARIOS (ID_USUARIO, NICKNAME, NOMBRE,  APELLIDOS, TELEFONO, CORREO, PASSWORD) VALUES (SEQ_IDUSER.NEXTVAL, 'marta11', 'Marta', 'Rodriguez', 777777771, 'marta4@gmail.com', '');
/*
Error que empieza en la línea: 124 del comando :
INSERT INTO USUARIOS (ID_USUARIO, NICKNAME, NOMBRE,  APELLIDOS, TELEFONO, CORREO, PASSWORD) VALUES (11, 'marta11', 'Marta', 'Rodriguez', '777777771', 'marta4@gmail.com', '')
Informe de error -
ORA-01400: cannot insert NULL into ("CC16"."USUARIOS"."PASSWORD")

*/