
-- RESPECTO A LA TABLA USUARIOS --

-- ID_USUARIO NO LO AÑADIMOS EN LA INSTRUCCION DE AÑADIR YA QUE LO HEMOS IMPLEMENTADO QUE CADA VEZ QUE SE INSERTE UN USUARIO SE INCREMENTE AUTOMATICAMENTE

-- PRIMERO VAMOS AÑADIR EL ADMIN --

INSERT INTO USUARIOS (NICKNAME, NOMBRE, CORREO, PASSWORD, ROL_USUARIO) VALUES('admin', 'admin', 'admin@ucm', 'adminpass', 'ADMIN');

-- PARA AÑADIR UN USUARIO NORMAL NO HACE FALTA AÑADIR EL CAMPO ROL_USUARIO, PORQUE YA LO HEMOS IMPLEMENTADO DE TAL FORMA QUE CUANDO SE INSERTE UN USUARIO
-- SE PONGA POR DEFECTO EN ESE CAMPO: USER.

INSERT INTO USUARIOS (NICKNAME, NOMBRE, CORREO, PASSWORD) VALUES('alv1', 'Alvaro', 'alvcarpi@ucm', '1111');
INSERT INTO USUARIOS (NICKNAME, NOMBRE, CORREO, PASSWORD) VALUES('jhce2', 'Jhimmy Ender', 'jcandela@ucm.es', '2222');
INSERT INTO USUARIOS (NICKNAME, NOMBRE, CORREO, PASSWORD) VALUES('jvp3', 'Jorge', 'jvalma01@ucm.es', '3333');
INSERT INTO USUARIOS (NICKNAME, NOMBRE, CORREO, PASSWORD) VALUES('iif4', 'Iker', 'ikeriban@ucm.es', '4444');
INSERT INTO USUARIOS (NICKNAME, NOMBRE, CORREO, PASSWORD) VALUES('atc5', 'Alberto', 'alberture@ucm.es', '5555');
INSERT INTO USUARIOS (NICKNAME, NOMBRE, CORREO, PASSWORD) VALUES('jjjj6', 'Jonathan Jose', 'jonathanj@ucm.es', '6666');
