
DROP TABLE JUGADORES;
DROP TABLE EQUIPOS;
DROP TABLE DEPORTES;
DROP TABLE USUARIOS;


CREATE TABLE DEPORTES
(
    ID_DEPORTE NUMBER(10) PRIMARY KEY,
    NOMBRE_DEPORTE VARCHAR(30) NOT NULL UNIQUE, 
    NUMERO_MAXIMO_JUGADORES NUMBER(3),
    DURACION_MIN NUMBER(5) 
);

CREATE TABLE USUARIOS
(
    ID_USUARIO NUMBER(10) PRIMARY KEY,
    NICKNAME VARCHAR(15) NOT NULL UNIQUE,
    NOMBRE VARCHAR(30) NOT NULL,
    APELLIDOS VARCHAR(30) NOT NULL,
    TELEFONO NUMBER(9) NULL,
    CORREO VARCHAR(50) NOT NULL UNIQUE,
    PASSWORD VARCHAR(15) NOT NULL  
);



       
CREATE TABLE EQUIPOS
(
    ID_EQUIPO NUMBER(10) PRIMARY KEY,
    DEPORTE NUMBER(10),
    NOMBRE_EQUIPO VARCHAR(30) NOT NULL UNIQUE,
    FOREIGN KEY (DEPORTE) REFERENCES DEPORTES(ID_DEPORTE)ON DELETE CASCADE
);


CREATE TABLE JUGADORES 
(
    ID_JUGADOR NUMBER(10) PRIMARY KEY,
    EQUIPO NUMBER(10) NULL,
    USUARIO NUMBER (10) NULL,
    FOREIGN KEY (USUARIO) REFERENCES USUARIOS(ID_USUARIO)ON DELETE CASCADE,
    FOREIGN KEY (EQUIPO) REFERENCES EQUIPOS(ID_EQUIPO)ON DELETE CASCADE
 );
 

-- CREAR SECUENCIAS --

-- SECUENCIA ID_USUARIO --
CREATE SEQUENCE seq_iduser
MINVALUE 1
START WITH 1
INCREMENT BY 1
CACHE 30;

-- SECUENCIA ID_DEPORTES --
CREATE SEQUENCE seq_iddeporte
MINVALUE 1
START WITH 880001
INCREMENT BY 1
CACHE 7;

-- SECUENCIA ID_EQUIPO --
CREATE SEQUENCE seq_idequipo
MINVALUE 1
START WITH 550001
INCREMENT BY 1
CACHE 20;

--SECUENCIA ID_JUGADOR --
CREATE SEQUENCE seq_idjugador
MINVALUE 1
START WITH 330001
INCREMENT BY 1
CACHE 70;

INSERT INTO USUARIOS VALUES(SEQ_IDUSER.NEXTVAL,'alv1', 'Alvaro', 'Carpizo Garcia', 611111111, 'alvcarpi@ucm', '1111');
INSERT INTO USUARIOS VALUES(SEQ_IDUSER.NEXTVAL, 'jhce2','Jhimmy Ender', 'Candela Espinosa', 622222222, 'jcandela@ucm.es', '2222');
INSERT INTO USUARIOS VALUES(SEQ_IDUSER.NEXTVAL, 'jvp3','Jorge', 'Valsameda Plasencia', 633333333, 'jvalma01@ucm.es', '3333');
INSERT INTO USUARIOS VALUES(SEQ_IDUSER.NEXTVAL, 'iif4','Iker', 'Ibañez FLores', 644444444, 'ikeriban@ucm.es', '4444');
INSERT INTO USUARIOS VALUES(SEQ_IDUSER.NEXTVAL, 'atc5','Alberto', 'Turegano Castedo', 655555555, 'alberture@ucm.es', '5555');
INSERT INTO USUARIOS VALUES(SEQ_IDUSER.NEXTVAL, 'jjjj6', 'Jonathan Jose', 'Jimenez Jimenez', 666666666, 'jonathanj@ucm.es', '6666');
 

INSERT INTO DEPORTES VALUES(SEQ_IDDEPORTE.NEXTVAL, 'BALONCESTO', 10, 40);
INSERT INTO DEPORTES VALUES(SEQ_IDDEPORTE.NEXTVAL, 'FUTBOL', 20, 90);
INSERT INTO DEPORTES VALUES(SEQ_IDDEPORTE.NEXTVAL, 'BEISBOL', 10, 60);
INSERT INTO DEPORTES VALUES(SEQ_IDDEPORTE.NEXTVAL, 'BALONMANO', 15, 40);

 
INSERT INTO EQUIPOS VALUES (SEQ_IDEQUIPO.NEXTVAL, 880001, 'BULL');
INSERT INTO EQUIPOS VALUES(SEQ_IDEQUIPO.NEXTVAL, 880002, 'REAL MADRID');
INSERT INTO EQUIPOS VALUES(SEQ_IDEQUIPO.NEXTVAL, 880003, 'SALOU');

INSERT INTO JUGADORES VALUES(SEQ_IDJUGADOR.NEXTVAL, 550001, 8);
INSERT INTO JUGADORES VALUES(SEQ_IDJUGADOR.NEXTVAL, 550001, 9);
INSERT INTO JUGADORES VALUES(SEQ_IDJUGADOR.NEXTVAL, 550002, 10);
INSERT INTO JUGADORES VALUES(SEQ_IDJUGADOR.NEXTVAL, 550002, 11);
INSERT INTO JUGADORES VALUES(SEQ_IDJUGADOR.NEXTVAL, 550003, 12);
INSERT INTO JUGADORES VALUES(SEQ_IDJUGADOR.NEXTVAL, 550003, 13);

COMMIT;

DELETE FROM USUARIOS;
DELETE FROM EQUIPOS;
DELETE FROM DEPORTES;
DELETE FROM JUGADORES;


SELECT * FROM USUARIOS;
SELECT * FROM DEPORTES;
SELECT * FROM EQUIPOS;
SELECT * FROM JUGADORES;

-- SI BORRAMOS UN USUARIO DE LA TABLA USUARIOS, SE DEBE DE BORRAR TODOS LOS EQUIPOS QUE PERTENECE EN LA TABLA JUGADORES.
DELETE FROM usuarios WHERE nombre = 'Alvaro';
-- SI BORRAMOS SOLO DE UN EQUIPO UN USUARIO REGISTRADO.
DELETE FROM jugadores WHERE id_jugador = 9002;
--  SI ELIMINAMOS UN EQUIPO DE LA TABLA EQUIPOS, SE DEBE BORRAR LOS JUGADORES QUE PERTENECIAN A ESE EQUIPO DE LA TABLA JUGADORES.
DELETE FROM equipos WHERE nombre_equipo = 'REAL MADRID';

-- SI BORRAMOS UN DEPORTE DE LA TABLA DEPORTES, SE DEBE BORRAR TODOS LOS EQUIPOS CORRESPONDIENTES DE ESE DEPORTE EN LA TABLA EQUIPOS 
--Y POR CONSIGUENTE SE BORRA TODOS LOS JUGADORES QUE JUGAN EN ALGUN EQUIPO DE ESE DEPORTE DE LA TABLA JUGADORES
DELETE FROM deportes WHERE nombre_deporte = 'BEISBOL';

/*
-- AÑADIR LA COLUMNA PASSWORD EN LA TABLA USUARIOS
ALTER TABLE USUARIOS ADD PASSWORD VARCHAR(15)NOT NULL;

--ELIMINAR COLUMNA PASSWORD 
ALTER TABLE USUARIOS DROP COLUMN PASSWORD;

-- ACTUALIZAR LOS DATOS EN EL CAMPO PASSWORD DEPENDIENTE EL NOMBRE QUE TIENEN.
UPDATE usuarios SET  PASSWORD = '1111' WHERE  NOMBRE = 'Alvaro';
UPDATE usuarios SET  PASSWORD = '2222' WHERE  NOMBRE = 'Jhimmy Ender';
UPDATE usuarios SET  PASSWORD = '3333' WHERE  NOMBRE = 'Jorge';
UPDATE usuarios SET  PASSWORD = '4444' WHERE  NOMBRE = 'Iker';
UPDATE usuarios SET  PASSWORD = '5555' WHERE  NOMBRE = 'Alberto';
UPDATE usuarios SET  PASSWORD = '6666' WHERE  NOMBRE = 'Jonathan Jose';
*/
COMMIT;

--CONSULTAS A REALIZAR
SELECT * FROM usuarios;
SELECT * FROM equipos;
SELECT * FROM deportes;
SELECT * FROM jugadores;

-- INSERTAR UN NUEVO USUARIO --
INSERT INTO USUARIOS (ID_USUARIO, NICKNAME, NOMBRE,  APELLIDOS, TELEFONO, CORREO, PASSWORD) VALUES (SEQ_IDUSER.NEXTVAL, 'sofi7', 'Sofia', 'Garcia Lopez',677777777, 'susanalopez@gmail.com', 'ss77');
INSERT INTO USUARIOS (ID_USUARIO, NICKNAME, NOMBRE,  APELLIDOS, TELEFONO, CORREO, PASSWORD) VALUES (SEQ_IDUSER.NEXTVAL, 'sofi8', 'Sofia', 'Garcia Lopez', '','susanaalegria@gmail.com', 'ss77');
INSERT INTO USUARIOS (ID_USUARIO, NICKNAME, NOMBRE,  APELLIDOS, TELEFONO, CORREO, PASSWORD) VALUES (SEQ_IDUSER.NEXTVAL, 'juli9', 'Julia', 'Hernandez Blanco', '', 'susanaalegria@gmail.com', 'yy44');
INSERT INTO USUARIOS (ID_USUARIO, NICKNAME, NOMBRE,  APELLIDOS, TELEFONO, CORREO, PASSWORD) VALUES (SEQ_IDUSER.NEXTVAL, 'robert10', 'Roberto', 'Ruiz', '', 'robertoruiz@gmail.com', '2223B');
INSERT INTO USUARIOS (ID_USUARIO, NICKNAME, NOMBRE,  APELLIDOS, TELEFONO, CORREO, PASSWORD) VALUES (SEQ_IDUSER.NEXTVAL, 'marta11', 'Marta', 'Rodriguez', '777777771', 'marta4@gmail.com', '');
INSERT INTO USUARIOS (ID_USUARIO, NICKNAME, NOMBRE,  APELLIDOS, TELEFONO, CORREO, PASSWORD) VALUES (SEQ_IDUSER.NEXTVAL, 'marta11', 'Marta', 'Rodriguez', '777777771', '', 'dsds');